name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# TODO: Add more jobs for testing, etc.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        npm i -g npm@^7
        npm i
    - name: Compile source files
      run: |
        npm run compile:css
        npm run compile:js
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: axelrindle/github-starred-index:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
    # - name: Update repo description
    #   uses: peter-evans/dockerhub-description@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: axelrindle/github-starred-index
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
